services:
  jobmanager:
    image: zablondev/flink-iceberg:latest
    hostname: jobmanager
    container_name: jobmanager
    depends_on:
      iceberg-rest:
        condition: service_healthy
      
    networks:
      iceberg_net:
    ports:
      - "8082:8081"
    command: jobmanager
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/overview"]
      start_period: 30s
      interval: 5s
      timeout: 3s
      retries: 5
    environment:
      FLINK_PROPERTIES: |
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 4
        parallelism.default: 2
      AWS_REGION: us-east-1
      AWS_ACCESS_KEY_ID: admin
      AWS_SECRET_ACCESS_KEY: password
      S3_ENDPOINT: http://minio:9000


  taskmanager:
    image: zablondev/flink-iceberg:latest
    hostname: taskmanager
    command: taskmanager

    depends_on:
      jobmanager:
        condition: service_healthy

    networks:
      iceberg_net:

    environment:
      FLINK_PROPERTIES: |
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 4
        parallelism.default: 2

      AWS_REGION: us-east-1
      AWS_ACCESS_KEY_ID: admin
      AWS_SECRET_ACCESS_KEY: password
      S3_ENDPOINT: http://minio:9000


  iceberg-rest:
    image: apache/iceberg-rest-fixture
    hostname: iceberg-rest
    depends_on:
      create-bucket:
        condition: service_completed_successfully
    networks:
      iceberg_net:
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8181/v1/config"]
      interval: 5s
      timeout: 3s
      retries: 5
    environment:
      AWS_REGION: us-east-1
      CATALOG_WAREHOUSE: s3://warehouse/
      CATALOG_IO__IMPL: org.apache.iceberg.aws.s3.S3FileIO
      CATALOG_S3_ENDPOINT: http://minio:9000
      CATALOG_S3_ACCESS__KEY__ID: admin
      CATALOG_S3_SECRET__ACCESS__KEY: password
      CATALOG_S3_PATH_STYLE_ACCESS: "true"


  minio:
    image: minio/minio
    hostname: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
      MINIO_DOMAIN: minio
    networks:
      iceberg_net:
        aliases:
          - warehouse.minio
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 5s
      retries: 5

    volumes:
      - minio_data:/data


  create-bucket:
    image: minio/mc

    depends_on:
      minio:
        condition: service_healthy

    networks:
      iceberg_net:

    entrypoint: >
      /bin/sh -c "
      until (/usr/bin/mc alias set minio http://minio:9000 admin password)
      do
        echo 'waiting for minio...' && sleep 1;
      done;

      /usr/bin/mc mb minio/warehouse --ignore-existing;
      /usr/bin/mc policy set public minio/warehouse;
      exit 0;
      "

  trino-coordinator:
    image: trinodb/trino:476
    container_name: trino-coordinator
    ports:
      - "8085:8080"
    volumes:
      - ./trino/etc:/etc/trino
    networks:
      iceberg_net:
    depends_on:
      - iceberg-rest
      - minio

  kafka:
    image: apache/kafka:3.9.0
    container_name: kafka
    networks:
      iceberg_net:
    ports:
        - "9092:9092"
        - "29092:29092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093,PLAINTEXT_HOST://:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_LOG_DIRS: /tmp/kraft

    volumes:
      - kafka_data:/tmp/kraft-combined-logs



  akhq:
    image: tchiotludo/akhq:0.25.0
    hostname: akhq
    container_name: akhq
    networks:
      iceberg_net:
    depends_on:
      - kafka
    ports:
      - "8087:8080"
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            docker-kafka-server:
              properties:
                bootstrap.servers: "kafka:9092"

  java-app:
    image: zablondev/data-generator:latest
    container_name: java-app
    depends_on:
      - kafka
    networks:
      iceberg_net:


networks:
  iceberg_net:
    driver: bridge

volumes:
  minio_data:
  kafka_data:

